version: 2

builds:
  - binary: git-daily
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

brews:
  - repository:
      owner: peaster
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    name: git-daily
    homepage: https://github.com/peaster/git-daily
    description: Extract your git activity across repos for a specific period of time.
    license: MIT
    install: |
      bin.install "git-daily"
    test: |
      system bin/"git-daily", "--help"

nfpms:
  - id: git-daily
    package_name: git-daily
    vendor: peaster
    homepage: https://github.com/peaster/git-daily
    maintainer: peaster
    description: Extract your git activity across repos for a specific day.
    license: MIT
    formats:
      - deb
    bindir: /usr/bin
    section: utils
    priority: optional
    contents:
      - src: LICENSE
        dst: /usr/share/doc/git-daily/LICENSE
      - src: README.md
        dst: /usr/share/doc/git-daily/README.md
    dependencies:
      - git

aurs:
  - name: git-daily-bin
    homepage: https://github.com/peaster/git-daily
    description: Extract your git activity across repos for a specific day.
    maintainers:
      - "peaster"
    license: MIT
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/git-daily-bin.git"
    depends:
      - git
    package: |-
      install -Dm755 "./git-daily" "${pkgdir}/usr/bin/git-daily"
      install -Dm644 "./LICENSE"   "${pkgdir}/usr/share/licenses/git-daily-bin/LICENSE"
      install -Dm644 "./README.md" "${pkgdir}/usr/share/doc/git-daily-bin/README.md"
    commit_author:
      name: peaster
      email: git@peaster.io
